### ISSUE TITLE
tests fail randomly

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ttl#23]
It probably varies depending on your computer but according to my measurements they happen about every 25th on average, i.e. 4 out of 100 tests (on my machine that is).

```
# test prolong entry life with additional put
ok 64 no error on open()
ok 65 no error
ok 66 contains {bar, barvalue}
ok 67 contains {foo, foovalue}
ok 68 contains {\xffttl\xff\d{13}!bar, bar}
ok 69 contains {ÿttlÿbar, \d{13}}
ok 70 no error
ok 71 contains {bar, barvalue}
ok 72 contains {foo, foovalue}
ok 73 contains {\xffttl\xff\d{13}!bar, bar}
ok 74 contains {ÿttlÿbar, \d{13}}
ok 75 no error
ok 76 contains {bar, barvalue}
ok 77 contains {foo, foovalue}
ok 78 contains {\xffttl\xff\d{13}!bar, bar}
ok 79 contains {ÿttlÿbar, \d{13}}
ok 80 no error
ok 81 contains {bar, barvalue}
ok 82 contains {foo, foovalue}
not ok 83 does not contain {\xffttl\xff\d{13}!bar, bar}
  ---
    operator: fail
    at: contains (/home/lms/src/leveldb-repos/node-level-ttl/test.js:63:12)
  ...
not ok 84 does not contain {ÿttlÿbar, \d{13}}
  ---
    operator: fail
    at: contains (/home/lms/src/leveldb-repos/node-level-ttl/test.js:63:12)
  ...
```

Is there some way we can make the tests more stable and less timing critical?

This feels like a race condition where either a batch of ttl meta data keys haven't had the time to be written before they are being read by the test *or* that they have in fact been deleted just before we're reading them in the tests (e.g. in `db2arr(createReadStream, t, function (err, arr) {})`

**Comment by ekristen** [comment]
Since most of the tests are written in the 10s of milliseconds, it would probably be wise to bump them all up into the 100s of milliseconds or higher.

**Comment by ekristen** [comment]
PR https://github.com/rvagg/node-level-ttl/pull/25 goes a long way to fix this, but it can still fail periodically.

**Comment by ralphtheninja** [comment]
I'll leave this open for a while longer.

**Comment by ralphtheninja** [comment]
I've figured out why this happens now. The reason why the test fails is because the `createReadStream()` call [here](https://github.com/rvagg/node-level-ttl/blob/adb494829675e65e720b21bd81fc9952620d86f7/test.js#L194) might happen in between deleting the old meta data [here](https://github.com/rvagg/node-level-ttl/blob/adb494829675e65e720b21bd81fc9952620d86f7/level-ttl.js#L159-L167) and updating it with new meta data [here](https://github.com/rvagg/node-level-ttl/blob/adb494829675e65e720b21bd81fc9952620d86f7/level-ttl.js#L132-L140)

I have a fix for it but involves updating the code so it can keep track of when it's actually updating the meta data. If a user of the db can find that out, it can also avoid doing a `createReadStream()`.
