### ISSUE TITLE
Listening for expiring keys.

### ISSUE THREAD

**Issue by austinfrey** [Level/level-ttl#57]
Is there any way to listen for an expiring key event? I did not see it in the documentation but wanted to double check. I tried using `db.on('del',...)` but no luck. thanks

**Comment by austinfrey** [comment]
for future reference after looking at the `level-ttl` internals and realizing delete operations were part of a `batch` operation, listening for the `batch` event and filtering deletes was the way to go.
```
const level = require('level')
const ttl = require('level-ttl')

const db = level('.test.db')
const ttlDB = ttl(db, { checkFrequency: 500, defaultTTL: 1000 })

ttlDB.put('foo', 'bar')

ttlDB.on('batch', ops => {
    if (op[0].type === 'del') console.log(ops)
})

setTimeout(() => {}, 5000)
```

**Comment by vweevers** [comment]
Oh, sorry we didn't respond @austinfrey. Missed this one. Glad you found a solution!

**Comment by austinfrey** [comment]
@vweevers no biggie :)
