### ISSUE TITLE
Use subleveldown instead of level-sublevel

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ttl#70]
Not really sure what to do with `'level-sublevel/bytewise'` yet:

https://github.com/Level/level-ttl/blob/f8e10d1afcf7383a6035be02be69b74209a371fd/test.js#L7

and

https://github.com/Level/level-ttl/blob/f8e10d1afcf7383a6035be02be69b74209a371fd/test.js#L715

I might comment the corresponding test (a single test) out for now and solve the low hanging fruit first.

**Comment by vweevers** [comment]
`bytewise` can be used as an encoding :)
