### ISSUE TITLE
Use 'proper' version ranges for dependencies

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ttl#73]
See

https://github.com/Level/level-ttl/blob/8ee3b02def12c9492f51929202f696b965d7f440/package.json#L21-L24

and

https://github.com/Level/level-ttl/blob/8ee3b02def12c9492f51929202f696b965d7f440/package.json#L33

**Comment by TehShrike** [comment]
What's the longer version of this issue description?

**Comment by ralphtheninja** [comment]
@TehShrike Ah, sorry. I'm just making quick issues for the backlog and didn't think anyone was that interested. Updated.

**Comment by TehShrike** [comment]
I've been clicking into these to see what's going on, but they're kind of inscrutable :sweat_smile:
